app/alerts/models.py
# -*- coding: UTF-8 -*-
from database import db
from app.alerts import constants as ALERT
import datetime
from config import APP_DEV


class Alert(db.Model):
    __tablename__ = 'alert'
    id = db.Column(db.Integer, primary_key=True)
    schedule_id = db.Column(db.Integer)
    date = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    alert = db.Column(db.UnicodeText)
    post = db.Column(db.SmallInteger, default=ALERT.SENT)
    archived = db.Column(db.Boolean, default=False)

    def __init__(self, schedule_id, archived=False, alert=None, post=None):
        self.post = post
        self.alert = alert
        self.archived = archived
        self.schedule_id = schedule_id


class Scheduler(db.Model):
    __tablename__ = 'scheduler'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(128), nullable=False, unique=True)
    target = db.Column(db.String(128), nullable=False)
    cycle = db.Column(db.Integer, default=5, nullable=False)
    command = db.Column(db.UnicodeText, nullable=False)
    status = db.Column(db.Boolean, default=False)
    post_status = db.Column(db.Boolean, default=False)
    post_addr = db.Column(db.String(256))
    post_name = db.Column(db.String(50), default='output')
    post_protected = db.Column(db.Boolean, default=False)
    post_username = db.Column(db.String(50))
    post_password = db.Column(db.String(50))

    def __init__(self, name, cycle, command, target, status=False, post_status=False, post_addr=None, post_name=None,
                 post_protected=None, post_username=None, post_password=None):
        self.name = name
        self.cycle = cycle
        self.command = command
        self.target = target
        self.status = status
        self.post_status = post_status
        self.post_addr = post_addr
        self.post_name = post_name
        self.post_protected = post_protected
        self.post_username = post_username
        self.post_password = post_password


def alerts_default():
    if not APP_DEV:
        return True
    alert1 = Alert(1, False, '{"test1": "somedata"}', True)
    db.session.add(alert1)
    alert2 = Alert(1, False, '{"test1": "somedata"}', True)
    db.session.add(alert2)
    alert3 = Alert(2, False, '{"test1": "somedata"}', True)
    db.session.add(alert3)
    alert4 = Alert(2, False, '{"test1": "somedata"}', True)
    db.session.add(alert4)
    alert5 = Alert(2, True, '{"test2": "somedata"}', False)
    db.session.add(alert5)
    db.session.commit()
    return True


def add_alert(schedule_id, alert, post):
    alert = Alert(schedule_id, False, alert, post)
    db.session.add(alert)
    db.session.commit()
    return True


def get_alerts(number_of_alerts):
    output = []
    for alerts, schedulers in db.session.query(Alert, Scheduler).filter(Alert.archived == 0). \
            order_by(Alert.id.desc()).outerjoin(Scheduler, Alert.schedule_id == Scheduler.id).limit(
            number_of_alerts):
        output.append([alerts.id, str(alerts.date)[0:-7], schedulers.name, alerts.post, schedulers.target])
    return output


def get_alert(alert_id):
    return db.session.query(Alert.alert).filter(Alert.id == alert_id).first()[0]


def get_archived_alerts(number_of_alerts):
    output = []
    for alerts, schedulers in db.session.query(Alert, Scheduler).filter(Alert.archived == 1). \
            order_by(Alert.id.desc()).outerjoin(Scheduler, Alert.schedule_id == Scheduler.id).limit(
            number_of_alerts):
        output.append([alerts.id, str(alerts.date)[0:-7], schedulers.name, alerts.post, schedulers.target])
    return output


def archive_alert(alert_id):
    db.session.query(Alert).filter(Alert.id == alert_id).update({'archived': True})
    db.session.commit()
    return True


def remove_alert(alert_id):
    db.session.query(Alert).filter(Alert.id == alert_id).delete()
    db.session.commit()
    return True


def remove_alerts_with_schedid(sched_id):
    db.session.query(Alert).filter(Alert.schedule_id == sched_id).delete()
    db.session.commit()
    return True


def archive_all_alerts():
    db.session.query(Alert).filter(Alert.archived == 0).update({'archived': True})
    db.session.commit()
    return True

app/alerts/views.py
from flask import Blueprint, render_template, request
from app.alerts.models import get_alerts, get_archived_alerts, get_alert, archive_alert, remove_alert, \
    archive_all_alerts
from app.settings.models import get_settings

mod = Blueprint('alerts', __name__, url_prefix='/alerts')


@mod.route('/')
def index():
    number_of_alerts = get_settings('ge')['ge-maxalerts']
    alerts = get_alerts(number_of_alerts)
    return render_template("alerts/alerts.html", title="Alerts", alerts=alerts)


@mod.route('/archive', methods=['GET', 'POST'])
def archive():
    if request.method == 'POST':
        if request.form.get('archive'):
            alert_id = request.form.get('archive')
            if archive_alert(alert_id):
                return '', 200
        if request.form.get('trash'):
            alert_id = request.form.get('trash')
            if remove_alert(alert_id):
                return '', 200
        if request.form.get('archive_all'):
            if archive_all_alerts():
                return '', 200
        else:
            return '', 400
    else:
        number_of_alerts = get_settings('ge')['ge-maxalerts']
        alerts_archived = get_archived_alerts(number_of_alerts)
        return render_template("alerts/archive.html", title="Alerts archive", alerts=alerts_archived)


@mod.route('/raw/<int:id>')
def show(id):
    alert = get_alert(id)
    if alert is not False:
        return render_template("alerts/raw.html", alert=str(alert)), 200
    else:
        raise ValueError('No data')

app/cleaner/views.py
from flask import Blueprint, render_template, request
from app.cleaner.models import remove_alerts_by_date
from app.settings.models import get_enabled_indexes

mod = Blueprint('cleaner', __name__, url_prefix='/cleaner')


@mod.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if request.form.get('cl-alias') is not None:
            daterange = request.form.get('daterange')
            if daterange is not None:
                date = daterange.split(' - ')
                start = date[0].split('/')
                end = date[1].split('/')
                date_start = start[2] + '-' + start[0] + '-' + start[1]
                date_end = end[2] + '-' + end[0] + '-' + end[1]

                print date_end, date_start

                remove_alerts_by_date(date_start, date_end)

        return render_template("cleaner/cleaner.html", title="Cleaner")
    else:
        return render_template("cleaner/cleaner.html", title="Cleaner")

app/templates/alerts/alerts.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block end_scripts %}
    <style>
        .modal-dialog {
            width: 90%;
            padding: 0;
            overflow-y: auto;
            max-height: 80%;
        }

        .modal-content {
            border-radius: 0;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container">
        <h3>Alerts</h3>

        <p>Listing of recent alerts</p>
        {% if alerts %}
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Alert rule</th>
                    <th>Target</th>
                    <th>Alert</th>
                    <th>POST Sent</th>
                    <th>Archive</th>
                </tr>
                </thead>
                <tbody>
                {% for alert in alerts %}
                    <tr>
                        <td>{{ alert[0] }}</td>
                        <td>{{ alert[1] }}</td>
                        <td>{{ alert[2] }}</td>
                        <td>{{ alert[4] }}</td>
                        <td><a data-toggle="modal" href="/alerts/raw/{{ alert[0] }}"
                               data-target="#myModal"><span class="glyphicon glyphicon-comment"></span></a></td>
                        {% if alert[3] == 0 %}
                            <td><span title="Sent" class="glyphicon glyphicon-ok"></span></td>{% endif %}
                        {% if alert[3] == 1 %}
                            <td></td>{% endif %}
                        {% if alert[3] == 2 %}
                            <td><span title="Error!" class="glyphicon glyphicon-remove"></span></td>{% endif %}
                        <td><a href="javascript:sendData({archive: {{ alert[0] }}})">
                            <span title="Archive" class="glyphicon glyphicon-briefcase"></span></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="text-center">So far nothing there.</div>
        {% endif %}
        <div class="text-right">
            <a href="javascript:sendData({archive_all: true})" class="btn btn-sm btn-default" role="button">Archive all
                alerts</a>
            <a href="{{ url_for('alerts.archive') }}" class="btn btn-sm btn-default" role="button">Archive</a>
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Alert Message</h4>
                </div>
                <div class="modal-body">
                    <div class="te"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function sendData(data) {
            var XHR = new XMLHttpRequest();
            var FD = new FormData();
            for (name in data) {
                FD.append(name, data[name]);
            }
            XHR.addEventListener('load', function (event) {
                reload();
            });
            XHR.addEventListener('error', function (event) {
                alert('Oups! Something went wrong.');
            });
            XHR.open('POST', '/alerts/archive');
            XHR.send(FD);
        }

        function reload() {
            window.location.reload(false);
        }
        $('#myModal').on('hidden', function () {
            $(this).removeData('modal');
        });
    </script>
{% endblock %}

app/templates/alerts/archive.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block end_scripts %}
    <style>
        .modal-dialog {
            width: 90%;
            padding: 0;
            overflow-y: auto;
            max-height: 80%;
        }

        .modal-content {
            border-radius: 0;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container">
        <h3>Alerts archive</h3>

        <p>Listing of archived alerts</p>
        {% if alerts %}
            <table class="table table-condensed">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Date</th>
                    <th>Alert rule</th>
                    <th>Target</th>
                    <th>Alert</th>
                    <th>POST Sent</th>
                    <th>Trash</th>
                </tr>
                </thead>
                <tbody>
                {% for alert in alerts %}
                    <tr>
                        <td>{{ alert[0] }}</td>
                        <td>{{ alert[1] }}</td>
                        <td>{{ alert[2] }}</td>
                        <td>{{ alert[4] }}</td>
                        <td><a data-toggle="modal" href="/alerts/raw/{{ alert[0] }}"
                               data-target="#myModal"><span class="glyphicon glyphicon-comment"></span></a></td>
                        {% if alert[3] == 0 %}
                            <td><span title="Sent" class="glyphicon glyphicon-ok"></span></td>{% endif %}
                        {% if alert[3] == 1 %}
                            <td></td>{% endif %}
                        {% if alert[3] == 2 %}
                            <td><span title="Error!" class="glyphicon glyphicon-remove"></span></td>{% endif %}
                        <td><a href="javascript:sendData({trash: {{ alert[0] }}})">
                            <span title="Remove" class="glyphicon glyphicon-trash"></span></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="text-center">So far nothing there.</div>
        {% endif %}
        <div class="text-right">
            <a href="{{ url_for('cleaner.index') }}" class="btn btn-sm btn-default" role="button">Cleaner</a>
            <a href="{{ url_for('alerts.index') }}" class="btn btn-sm btn-default" role="button">Alerts</a>
        </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Alert Message</h4>

                </div>
                <div class="modal-body">
                    <div class="te"></div>
                </div>
            </div>
        </div>
    </div>
    <script>
        function sendData(data) {
            var XHR = new XMLHttpRequest();
            var FD = new FormData();
            for (name in data) {
                FD.append(name, data[name]);
            }
            XHR.addEventListener('load', function (event) {
                reload();
            });
            XHR.addEventListener('error', function (event) {
                alert('Oups! Something went wrong.');
            });
            XHR.open('POST', '/alerts/archive');
            XHR.send(FD);
        }

        function reload() {
            window.location.reload(false);
        }
        $('#myModal').on('hidden', function () {
            $(this).removeData('modal');
        });
    </script>
{% endblock %}

app/templates/alerts/raw.html
<!DOCTYPE html>
<html lang="en">
<head>
    <style>#json {
        white-space: pre-wrap;
        font-family: monospace;
        font-size: 0.9em;
    }
    </style>
</head>
<body>
<div id="json"></div>

<script>
    var obj = {{ alert|safe }}
    document.getElementById("json").appendChild(document.createTextNode(JSON.stringify(obj, null, 4)));
</script>
</body>
</html>