app/scheduler/models.py
# -*- coding: UTF-8 -*-
from database import db
from config import APP_DEV
from app.alerts.models import Scheduler, remove_alerts_with_schedid


def scheduler_default():
    if not APP_DEV:
        return True
    scheduler1 = Scheduler('Any 404 on 192.168.1.154', 5,
                           '{"query":{"filtered":{"query":{"bool":{"must":[{"match":{"@fields.status":"404"}},'
                           '{"match":{"host":"192.168.1.204"}}]}},'
                           '"filter":{"range":{"@timestamp":{"from":"now-5m","to":"now"}}}}}}',
                           'access', False, True,
                           'http://192.168.1.117/post/', 'output')
    db.session.add(scheduler1)
    scheduler2 = Scheduler('Time over 1sec on 192.168.1.154', 60,
                           '{"query":{"filtered":{"query":{"bool":{"must":[{"match":{"host":"192.168.1.204"}}]}},'
                           '"filter":{"range":{"@timestamp":{"from":"now-60m","to":"now"},'
                           '"@fields.request_time":{"gte":1}}}}}}',
                           'access', False, False,
                           'http://192.168.1.117/post/', 'output')
    db.session.add(scheduler2)
    db.session.commit()
    return True


def add_scheduler(data):
    new = Scheduler(data['sh-name'], data['sh-cycle'], data['sh-script'], data['sh-target'], data['sh-enabled'],
                    data['sh-post-enabled'],
                    data['sh-post-addr'], data['sh-post-output'], data['sh-post-protected'], data['sh-post-username'],
                    data['sh-post-password'])
    db.session.add(new)
    db.session.commit()
    return True


def update_scheduler_using_id(scheduler_id, data):
    db.session.query(Scheduler).filter(Scheduler.id == scheduler_id).update(
            {"name": data['sh-name'], "cycle": data['sh-cycle'], "command": data['sh-script'],
             "target": data['sh-target'],
             "status": data['sh-enabled'], "post_status": data['sh-post-enabled'], "post_addr": data['sh-post-addr'],
             "post_name": data['sh-post-output'], "post_protected": data['sh-post-protected'],
             "post_username": data['sh-post-username'], "post_password": data['sh-post-password']})
    db.session.commit()
    return True


def update_scheduler_using_name(name, data):
    db.session.query(Scheduler).filter(Scheduler.name == name).update(
            {"name": data['sh-name'], "cycle": data['sh-cycle'], "command": data['sh-script'],
             "target": data['sh-target'], "status": data['sh-enabled'], "post_status": data['sh-post-enabled'],
             "post_addr": data['sh-post-addr'],
             "post_name": data['sh-post-output'], "post_protected": data['sh-post-protected'],
             "post_username": data['sh-post-username'], "post_password": data['sh-post-password']})
    db.session.commit()
    return True


def get_schedulers_list(number_of_schedulers):
    output = []
    for instance in db.session.query(Scheduler).order_by(Scheduler.id).limit(number_of_schedulers):
        output.append([instance.id, instance.name, instance.status, instance.post_status,
                       instance.cycle, instance.target])
    return output


def get_scheduler(scheduler_id):
    for instance in db.session.query(Scheduler).filter(Scheduler.id == scheduler_id).order_by(Scheduler.id):
        return [instance.id, instance.name, instance.cycle, instance.command, instance.status,
                instance.post_status, instance.post_addr, instance.post_name, instance.post_protected,
                instance.post_username, instance.post_password, instance.target]


def remove_scheduler(scheduler_id):
    remove_alerts_with_schedid(scheduler_id)
    db.session.query(Scheduler).filter(Scheduler.id == scheduler_id).delete()
    db.session.commit()
    return True


def remove_scheduler_with_index(target):
    for instance in db.session.query(Scheduler).filter(Scheduler.target == target).order_by(Scheduler.id):
        remove_scheduler(instance.id)
    return True


def get_schedulers_with_index(index):
    array = []
    for instance in db.session.query(Scheduler).filter(Scheduler.status == 1).filter(Scheduler.target == index):
        array.append({"id": instance.id, "cycle": instance.cycle, "command": instance.command,
                      "post_status": instance.post_status, "post_addr": instance.post_addr, "name": instance.name,
                      "post_name": instance.post_name, "post_protected": instance.post_protected,
                      "post_username": instance.post_username, "post_password": instance.post_password})
    return array


def set_scheduler_status(scheduler_id, status):
    if status in [True, False]:
        db.session.query(Scheduler).filter(Scheduler.id == scheduler_id).update({"status": status})
        db.session.commit()
        return True

app/settings/models.py
from database import db
from ast import literal_eval
from config import APP_DEV
from app.scheduler.models import remove_scheduler_with_index


class Setting(db.Model):
    __tablename__ = 'setting'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    settings = db.Column(db.String(1000))

    def __init__(self, name=None, settings=None):
        self.name = name
        self.settings = settings

    def __repr__(self):
        return "Settings<name='%s', settings='%s'>" % (self.name, self.settings)


class Index(db.Model):
    __tablename__ = 'index'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True)
    enabled = db.Column(db.Boolean, default=False)
    schema = db.Column(db.UnicodeText)

    def __init__(self, name, schema=None, enabled=False):
        self.name = name
        self.schema = schema
        self.enabled = enabled

    def __repr__(self):
        return "Indexes<name='%s', enabled='%s'>" % (self.name, self.enabled)


def default_es_settings():
    es = Setting('es', '{"es-ip": "192.168.1.117", "es-port": 9200, "es-ssl": False, '
                       '"es-prot": False, "es-user": None, "es-password": None}')
    db.session.add(es)
    db.session.commit()
    return True


def default_ge_settings():
    ge = Setting('ge', '{"ge-ele": 150, "ge-maxalerts": 50, "ge-maxschedulers": 50}')
    db.session.add(ge)
    db.session.commit()
    return True


def default_index_settings():
    if not APP_DEV:
        return True
    index1 = Index(
            "access", "[{'name': 'Timestamp', 'alias': 'time', 'target': ['_source', '@timestamp']},"
                      "{'name': 'Host', 'alias': 'host', 'target': ['_source', 'host']},"
                      "{'name': 'Client', 'alias': 'client', 'target': ['_source', '@fields', 'remote_addr']},"
                      "{'name': 'Req. time', 'alias': 'req', 'target': ['_source', '@fields', 'request_time']},"
                      "{'name': 'Status', 'alias': 'status', 'target': ['_source', '@fields', 'status']},"
                      "{'name': 'URI', 'alias': 'uri', 'target': ['_source', '@fields', 'request_uri']}]",
            True)
    db.session.add(index1)
    db.session.commit()
    return True


def add_index(name):
    index = Index(name)
    db.session.add(index)
    db.session.commit()
    return True


def get_index_settings(name):
    try:
        query = db.session.query(Index).filter_by(name=name).first()
        return literal_eval(query.schema)
    except ValueError:
        return [{"name": '', "alias": '', "target": ''}]


def get_enabled_indexes():
    query = db.session.query(Index).filter_by(enabled=True)
    names = []
    for item in query:
        names.append(item.name)
    return names


def get_all_indexes(only_name=False):
    query = db.session.query(Index)
    names = []
    for item in query:
        if only_name:
            names.append(item.name)
        else:
            names.append([item.name, item.enabled])
    return names


def get_settings(name):
    query = db.session.query(Setting).filter_by(name=name).first()
    return literal_eval(query.settings)


def update_settings(name, settings):
    db.session.query(Setting).filter(Setting.name == name).update({'settings': str(settings)})
    db.session.commit()
    return True


def update_index_settings(name, settings):
    db.session.query(Index).filter(Index.name == name).update({'schema': str(settings)})
    db.session.commit()
    return True


def set_index_status(name, status):
    db.session.query(Index).filter(Index.name == name).update({'enabled': status})
    db.session.commit()
    return True


def remove_index_from_database(name):
    remove_scheduler_with_index(name)
    db.session.query(Index).filter(Index.name == name).delete()
    db.session.commit()
    return True

app/scheduler/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from app.scheduler.models import get_schedulers_list, get_scheduler, set_scheduler_status, remove_scheduler, \
    add_scheduler, update_scheduler_using_id
from app.settings.models import get_settings, get_all_indexes
from parse import parse_scheduler, parse_existing_scheduler
import json
from config import ALLOWED_CRON_TIMES

mod = Blueprint('scheduler', __name__, url_prefix='/scheduler')

cron_times = ALLOWED_CRON_TIMES


@mod.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if request.form.get('enable'):
            sch_id = request.form.get('enable')
            if set_scheduler_status(sch_id, True):
                return '', 200
        if request.form.get('disable'):
            sch_id = request.form.get('disable')
            if set_scheduler_status(sch_id, False):
                return '', 200
        if request.form.get('remove'):
            sch_id = request.form.get('remove')
            if remove_scheduler(sch_id):
                return '', 200
        else:
            return '', 400
    else:
        number_of_schedulers = get_settings('ge')['ge-maxschedulers']
        schedulers = get_schedulers_list(number_of_schedulers)
        return render_template("scheduler/scheduler.html", title="Scheduler", schedulers=schedulers,
                               cron_times=cron_times)


@mod.route('/new', methods=['GET', 'POST'])
def new():
    if request.method == 'POST':
        data = parse_scheduler(request.form)
        add_scheduler(data)

        return redirect(url_for('scheduler.index'))
    else:
        enabled_indexes = get_all_indexes()
        return render_template("scheduler/new.html", title="Scheduler", enabled_indexes=enabled_indexes,
                               cron_times=cron_times)


@mod.route('/edit/<int:id>', methods=['GET', 'POST'])
def edit_id(id):
    if request.method == 'POST':
        data = parse_scheduler(request.form)
        update_scheduler_using_id(id, data)
        return redirect(url_for('scheduler.index'))
    else:
        instance = get_scheduler(id)
        settings = parse_existing_scheduler(instance)

        enabled_indexes = get_all_indexes()
        return render_template("scheduler/edit.html", sch_id=id, title="Scheduler edit",
                               enabled_indexes=enabled_indexes,
                               settings=json.dumps(settings, ensure_ascii=False), cron_times=cron_times)


@mod.route('/clone/<int:id>')
def clone_id(id):
    instance = get_scheduler(id)
    settings = parse_existing_scheduler(instance, name=False)
    if settings is None:
        raise SystemError('Something wrong with scheduler array.')

    enabled_indexes = get_all_indexes()
    return render_template("scheduler/clone.html", id=id, title="Scheduler clone", enabled_indexes=enabled_indexes,
                           settings=json.dumps(settings, ensure_ascii=False), cron_times=cron_times)


@mod.route('/clone', methods=['POST'])
def clone():
    data = parse_scheduler(request.form)
    add_scheduler(data)
    return redirect(url_for('scheduler.index'))

app/settings/views.py
from flask import Blueprint, render_template, request, url_for, redirect
import app.settings.models as model
from app.settings.models import set_index_status, get_all_indexes, get_index_settings, \
    remove_index_from_database, add_index, update_index_settings
import json
from app import Connection
import parse

mod = Blueprint('settings', __name__, url_prefix='/settings')


@mod.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if Connection.check_connection():
            conn = Connection.get_indexes_info()
            indexes_avail = parse.parse_avail_indexes(conn)
            error = False
        else:
            indexes_avail = []
            error = 'No connection to Elasticsearch! Check your settings.'

        if request.form.get('enable'):
            index_name = request.form.get('enable')
            if set_index_status(index_name, True):
                return '', 200
            else:
                return '', 400
        if request.form.get('disable'):
            index_name = request.form.get('disable')
            if set_index_status(index_name, False):
                return '', 200
        if request.form.get('trash'):
            index_name = request.form.get('trash')
            if remove_index_from_database(index_name):
                return '', 200
        if request.form.get('add_index'):
            index_name = request.form.get('add_index')
            if index_name in indexes_avail:
                add_index(index_name)
                return '', 200
        parsed_form = parse.parse_post_settings(request.form)
        if parsed_form is not None:
            model.update_settings(parsed_form[0], parsed_form[1])
        ge = model.get_settings('ge')
        es = model.get_settings('es')
        ge.update(es)
        Connection.update_connection(es['es-ip'], es['es-port'])
        indexes = get_all_indexes()
        return render_template("settings/settings.html", title="Settings",
                               settings=json.dumps(ge, ensure_ascii=False), active='es', indexes=indexes, error=error)
    else:
        ge = model.get_settings('ge')
        es = model.get_settings('es')
        ge.update(es)
        if Connection.check_connection():
            conn = Connection.get_indexes_info()
            indexes_avail = parse.parse_avail_indexes(conn)
            indexes = get_all_indexes(True)
            indexes_avail = set(indexes_avail) - set(indexes)
            indexes = get_all_indexes()
            error = False
        else:
            indexes = get_all_indexes()
            indexes_avail = []
            error = 'No connection to Elasticsearch! Check your settings.'
        return render_template("settings/settings.html", title="Settings",
                               settings=json.dumps(ge, ensure_ascii=False), active='es', indexes=indexes,
                               indexes_avail=indexes_avail, error=error)


@mod.route('/<string:name>', methods=['GET', 'POST'])
def indexes(name):
    if request.method == 'POST':
        settings = parse.parse_index_settings(request.form)
        update_index_settings(name, settings)
        return redirect(url_for('settings.index') + '#indexes')
    else:
        if name not in get_all_indexes(True):
            raise SystemError('Index does not exists!')

        settings = json.dumps(get_index_settings(name))
        return render_template("settings/indexes.html", title="Settings", index_name=name, settings=settings)

app/templates/scheduler/clone.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
    <script type="application/json" id="initial-data">{{ settings|safe }}</script>

    <div class="container">
        <div class="page-header">
            <h4>Scheduler basic options</h4>
        </div>

        <form id="sh-form" role="form" action="{{ url_for('scheduler.clone') }}" method="post">
            <input type="hidden" name="sh-tab">

            <div class="form-group">
                <label for="inputsm">Scheduler name</label>
                <input class="form-control input-sm" type="text" name="sh-name" required>
            </div>
            <div class="form-group">
                <label for="inputsm">Target</label>
                <select class="form-control input-sm" name="sh-target" required>
                    {% for index in enabled_indexes %}
                    <option>{{ index[0] }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="inputsm">Cycle time (min)</label>
                <select class="form-control input-sm" name="sh-cycle" required>
                    {% for cron in cron_times %}
                    <option>{{ cron }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label for="comment">ES Script:</label>
                    <textarea class="form-control" rows="3" name="sh-script"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="sh-enabled">Scheduler enabled</label>
                </div>
            </div>
            <div class="page-header">
                <h4>Scheduler POST</h4>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="sh-post-enabled">POST Enabled</label>
                </div>
            </div>
            <div class="form-group">
                <label for="inputsm">Address</label>
                <input class="form-control input-sm" name="sh-post-addr" type="text">
            </div>
            <div class="form-group">
                <label for="inputsm">Output field name</label>
                <input class="form-control input-sm" name="sh-post-output" type="text" placeholder="output">
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="sh-post-protected">POST Protected</label>
                </div>
            </div>
            <div class="form-group">
                <label for="inputsm">Username</label>
                <input class="form-control input-sm" name="sh-post-username" type="text" placeholder="output">
            </div>
            <div class="form-group">
                <label for="inputsm">Password</label>
                <input class="form-control input-sm" name="sh-post-password" type="text" placeholder="output">
            </div>
            <input type="submit" class="btn btn-info" value="Submit Button">
        </form>
    </div>
    </div>

    <script>
        var d = JSON.parse(document.getElementById("initial-data").innerHTML);
        function formAuto(form) {
            var inputs = form.querySelectorAll("input, textarea, select");
            var c = "els=this;";
            var els = [];
            for (var i = 0; i < inputs.length; i++) {
                var memberName = inputs[i].getAttribute("name");
                if (memberName != null) {
                    var index = els.push(inputs[i]) - 1;
                    if (inputs[i].type == "checkbox")
                        c += "els[" + index + "].checked=json['" + memberName + "'];";
                    else
                        c += "els[" + index + "].value=json['" + memberName + "']||'';";
                }
            }
            return {
                fill: new Function("json", c).bind(els)
            }
        }
        var form_sh = formAuto(document.getElementById("sh-form"));
        form_sh.fill(d);
    </script>

{% endblock %}

app/templates/scheduler/edit.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
    <script type="application/json" id="initial-data">{{ settings|safe }}</script>

    <div class="container">
        <div class="page-header">
            <h4>Scheduler basic options</h4>
        </div>

        <form id="sh-form" role="form" action="{{ url_for('scheduler.edit_id', id=sch_id) }}" method="post">
            <input type="hidden" name="sh-tab">
            <input type="hidden" name="sh_id" value="{{ sch_id }}">

            <div class="form-group">
                <label for="inputsm">Scheduler name</label>
                <input class="form-control input-sm" type="text" name="sh-name" required>
            </div>
            <div class="form-group">
                <label for="inputsm">Target</label>
                <select class="form-control input-sm" name="sh-target" required>
                    {% for index in enabled_indexes %}
                    <option>{{ index[0] }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="inputsm">Cycle time (min)</label>
                <select class="form-control input-sm" name="sh-cycle" required>
                    {% for cron in cron_times %}
                    <option>{{ cron }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <div class="form-group">
                    <label for="comment">ES Script:</label>
                    <textarea class="form-control" rows="3" name="sh-script"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="sh-enabled">Scheduler enabled</label>
                </div>
            </div>
            <div class="page-header">
                <h4>Scheduler POST</h4>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="sh-post-enabled">POST Enabled</label>
                </div>
            </div>
            <div class="form-group">
                <label for="inputsm">Address</label>
                <input class="form-control input-sm" name="sh-post-addr" type="text">
            </div>
            <div class="form-group">
                <label for="inputsm">Output field name</label>
                <input class="form-control input-sm" name="sh-post-output" type="text" placeholder="output">
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label><input type="checkbox" name="sh-post-protected">POST Protected</label>
                </div>
            </div>
            <div class="form-group">
                <label for="inputsm">Username</label>
                <input class="form-control input-sm" name="sh-post-username" type="text" placeholder="output">
            </div>
            <div class="form-group">
                <label for="inputsm">Password</label>
                <input class="form-control input-sm" name="sh-post-password" type="text" placeholder="output">
            </div>
            <input type="submit" class="btn btn-info" value="Submit Button">
        </form>
    </div>
    </div>

    <script>
        var d = JSON.parse(document.getElementById("initial-data").innerHTML);
        function formAuto(form) {
            var inputs = form.querySelectorAll("input, textarea, select");
            var c = "els=this;";
            var els = [];
            for (var i = 0; i < inputs.length; i++) {
                var memberName = inputs[i].getAttribute("name");
                if (memberName != null) {
                    var index = els.push(inputs[i]) - 1;
                    if (inputs[i].type == "checkbox")
                        c += "els[" + index + "].checked=json['" + memberName + "'];";
                    else
                        c += "els[" + index + "].value=json['" + memberName + "']||'';";
                }
            }
            return {
                fill: new Function("json", c).bind(els)
            }
        }
        var form_sh = formAuto(document.getElementById("sh-form"));
        form_sh.fill(d);
    </script>

{% endblock %}

app/templates/scheduler/scheduler.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <h3>Scheduler</h3>

        <p>Scheduler management page</p>
        {% if schedulers %}
            <table class="table table-condensed text-center">
                <thead>
                <tr>
                    <th class="text-center">ID</th>
                    <th class="text-center">Rule name</th>
                    <th class="text-center">Target</th>
                    <th class="text-center">Status</th>
                    <th class="text-center">POST</th>
                    <th class="text-center">Run every (min)</th>
                    <th class="text-center">Settings</th>
                    <th class="text-center">Remove</th>
                </tr>
                </thead>
                <tbody>
                {% for scheduler in schedulers %}
                    <tr>
                        <td>{{ scheduler[0] }}</td>
                        <td>{{ scheduler[1] }}</td>
                        <td>{{ scheduler[5] }}</td>
                        {% if scheduler[2] == True -%}
                            <td><a href="javascript:sendData({disable: {{ scheduler[0] }}})"><span
                                    class="glyphicon glyphicon-check"></span></a>
                            </td>{% endif %}
                        {% if scheduler[2] == False -%}
                            <td><a href="javascript:sendData({enable: {{ scheduler[0] }}})"><span
                                class="glyphicon glyphicon-unchecked"></span></a>{% endif %}
                        {% if scheduler[3] == True -%}
                            <td><span title="Enabled" class="glyphicon glyphicon-ok"></span></td>{% endif %}
                        {% if scheduler[3] == False -%}
                            <td><span title="Disabled" class="glyphicon glyphicon-remove"></span></td>{% endif %}
                        <td>{{ scheduler[4] }}</td>
                        <td>
                            <a href="{{ url_for('scheduler.edit_id', id=scheduler[0]) }}">
                                <span title="Edit" class="glyphicon glyphicon-edit"></span></a>
                            <a href="{{ url_for('scheduler.clone_id', id=scheduler[0]) }}">
                                <span title="Clone" class="glyphicon glyphicon-share"></span></a>
                        </td>
                        <td>
                            <a href="javascript:sendData({remove: {{ scheduler[0] }}})">
                                <span title="Remove" class="glyphicon glyphicon-trash"></span></a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div id="modal-dialog-alias" class="modal">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header text-center">
                            <a href="#" data-dismiss="modal" aria-hidden="true" class="close">×</a>

                            <h3 class="center-block">Information</h3>
                        </div>
                        <div class="modal-body text-center">
                            <p>Are you sure?</p>

                            <p>Removing Scheduler is taking removing all alerts (even not archived) too!</p>
                        </div>
                        <div class="modal-footer text-center">
                            <div class="text-center">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                                <input type="submit" class="btn btn-danger" value="Clean & remove">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}
        {% endif %}
        <div class="text-right">
            <a href="{{ url_for('scheduler.new') }}" class="btn btn-sm btn-default" role="button">Add new</a>
        </div>
    </div>
    <div id="confirm" class="modal hide fade">
  <div class="modal-body">
    Are you sure?<br>
    <b>This will</b>
  </div>
  <div class="modal-footer">
    <button type="button" data-dismiss="modal" class="btn btn-primary" id="delete">Delete</button>
    <button type="button" data-dismiss="modal" class="btn">Cancel</button>
  </div>
</div>
    <script>
        function sendData(data) {
            var XHR = new XMLHttpRequest();
            var FD = new FormData();
            for (name in data) {
                FD.append(name, data[name]);
            }
            XHR.addEventListener('load', function (event) {
                reload();
            });
            XHR.addEventListener('error', function (event) {
                alert('Oups! Something goes wrong.');
            });
            XHR.open('POST', '/scheduler/');
            XHR.send(FD);
        }

        function reload() {
            window.location.reload(false);
        }
    $('a[name="remove_levels"]').on('click', function(e){
    var $form=$(this).closest('form');
    e.preventDefault();
    $('#modal-dialog-alias').modal({ backdrop: 'static', keyboard: false })
        .one('click', '#delete', function (e) {
            $form.trigger('submit');
        });
});
    </script>
{% endblock %}