app/alerts/views.py
from flask import Blueprint, render_template, request
from app.alerts.models import get_alerts, get_archived_alerts, get_alert, archive_alert, remove_alert, \
    archive_all_alerts
from app.settings.models import get_settings

mod = Blueprint('alerts', __name__, url_prefix='/alerts')


@mod.route('/')
def index():
    number_of_alerts = get_settings('ge')['ge-maxalerts']
    alerts = get_alerts(number_of_alerts)
    return render_template("alerts/alerts.html", title="Alerts", alerts=alerts)


@mod.route('/archive', methods=['GET', 'POST'])
def archive():
    if request.method == 'POST':
        if request.form.get('archive'):
            alert_id = request.form.get('archive')
            if archive_alert(alert_id):
                return '', 200
        if request.form.get('trash'):
            alert_id = request.form.get('trash')
            if remove_alert(alert_id):
                return '', 200
        if request.form.get('archive_all'):
            if archive_all_alerts():
                return '', 200
        else:
            return '', 400
    else:
        number_of_alerts = get_settings('ge')['ge-maxalerts']
        alerts_archived = get_archived_alerts(number_of_alerts)
        return render_template("alerts/archive.html", title="Alerts archive", alerts=alerts_archived)


@mod.route('/raw/<int:id>')
def show(id):
    alert = get_alert(id)
    if alert is not False:
        return render_template("alerts/raw.html", alert=str(alert)), 200
    else:
        raise ValueError('No data')

app/cleaner/views.py
from flask import Blueprint, render_template, request
from app.cleaner.models import remove_alerts_by_date
from app.settings.models import get_enabled_indexes

mod = Blueprint('cleaner', __name__, url_prefix='/cleaner')


@mod.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        if request.form.get('cl-alias') is not None:
            daterange = request.form.get('daterange')
            if daterange is not None:
                date = daterange.split(' - ')
                start = date[0].split('/')
                end = date[1].split('/')
                date_start = start[2] + '-' + start[0] + '-' + start[1]
                date_end = end[2] + '-' + end[0] + '-' + end[1]

                print date_end, date_start

                remove_alerts_by_date(date_start, date_end)

        return render_template("cleaner/cleaner.html", title="Cleaner")
    else:
        return render_template("cleaner/cleaner.html", title="Cleaner")

app/index/views.py
from flask import Blueprint, redirect, url_for

""" Disabled -- no time
from app.index.models import get_archived_alerts, get_all_alerts, get_enabled_schedulers, get_all_schedulers
from app import Connection
from parse import parse_elastic_info
from pprint import pprint



@mod.route('/', methods=['GET'])
def index():
    es_info = parse_elastic_info(Connection.get_elastic_info())
    all_alerts = get_all_alerts()
    arch_alerts = get_archived_alerts()
    get_enabled_sched = get_enabled_schedulers()
    get_all_sched = get_all_schedulers()
    alerts = {"all": all_alerts,
              "archived": arch_alerts,
              "unarchived": all_alerts - arch_alerts
              }
    sched = {"all": get_all_sched, "enabled": get_enabled_sched,
             "disabled": get_all_sched - get_enabled_sched}
    return render_template('index/index.html', title='Index', es_head=es_info[0], es_info=es_info[1], alerts=alerts,
                           sched=sched)
"""

mod = Blueprint('index', __name__, url_prefix='/')


@mod.route('/')
def index():
    return redirect(url_for('search.index'))

app/templates/405.html
<!-- extend base layout -->
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="error-template">
                <h1>Oops!</h1>
                <h2>Method Not Allowed</h2>
                <div class="error-details">You are doing something nasty!</div>
                <div class="error-actions">
                    <a href="{{ url_for('index.index') }}" class="btn btn-default btn-lg">
                        <span style="font-size:0.9em;" class="glyphicon glyphicon-home"></span> Take Me Home</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="/static/img/favicon.ico">
    {% if title %}
        <title>{{ title }} - LogAuditor</title>
    {% else %}
        <title>LogAuditor</title>
    {% endif %}
    {% block css %}
    {% endblock %}
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/navbar-fixed-top.css" rel="stylesheet">
</head>

<body>
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
{% block script %}
{% endblock %}
{% block top_scripts %}
{% endblock %}

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">LogAuditor</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('search.index') }}">Search</a></li>
                <li><a href="{{ url_for('alerts.index') }}">Alerts</a></li>
                <li><a href="{{ url_for('scheduler.index') }}">Scheduler</a></li>
                <li><a href="{{ url_for('cleaner.index') }}">Cleaner</a></li>
                <li><a href="{{ url_for('settings.index') }}">Settings</a></li>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>
{% block searchresults %}{% endblock %}

{% block end_scripts %}
{% endblock %}
</body>
</html>